src/elements/codelabs-card.html
src/ubuntu-tutorials-app.html

Codelabs tutorials should now be available on `/tutorial/`

Move tutorials to /tutorial/

---

src/codelabs-index.html

This method has been removed temporarily, and is causing a console error.

Remove reference to removed sort method

---

index.html

Change favicon
Add apple touch icons

Change favico

---

src/elements/codelabs-card.html

Remove right padding from duration
Remove overflowing outline on card links

Little fixes

---

src/codelabs-index.html
src/elements/codelabs-card.html

as per issue #21
Fix issue #21 
https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/21

Update intro copy

---

src/codelabs-page.html
src/codelabs/create-first-snap/index.ubuntu-template.html
src/ubuntu-tutorials-app.html

Move styles from bower components

move styles

---

src/codelabs/basic-snap-usage/index.ubuntu-template.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html

add further styles

---

src/codelabs/basic-snap-usage/index.ubuntu-template.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html
src/codelabs/create-first-snap/index.ubuntu-template.html

change primary

---

src/codelabs-page.html

change syntax

---

src/codelabs-index.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html

Fix card with on windows 10 IE11
Fixes https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/42

Fix card with for IE11

---

src/codelabs/basic-snap-usage/index.ubuntu-template.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html
src/codelabs/create-first-snap/index.ubuntu-template.html
src/codelabs/create-your-own-core-image/index.ubuntu-template.html
src/codelabs/setup-ubuntu-core-intel-joule/index.ubuntu-template.html

Override 4px left border with 1px border
Pop to a tutorial and make sure the notes and info blocks have a 1px border

Change borders to notes

---

index.html
src/codelabs-page.html
src/codelabs/basic-snap-usage/index.ubuntu-template.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html
src/codelabs/create-first-snap/index.ubuntu-template.html
src/codelabs/create-your-own-core-image/index.ubuntu-template.html
src/codelabs/setup-ubuntu-core-intel-joule/index.ubuntu-template.html
src/codelabs/using-intel-realsense-sdk/index.ubuntu-template.html
src/ubuntu-tutorials-app.html

Fix pre code blocks styling issue
Add google tracking code
Check that code blocks are the light variety in Chrome, they’re dark on live
Fix https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/55

Fix code blocks for Chrome

---

bower.json
src/codelabs-page.html
src/elements/codelabs-card.html
src/elements/time-pretty.html

Add tags and date to cards
Run polymer serve then head to http://localhost:8080 and make sure the date (at the top of the tutorial description) and the tags (at the bottom of the description) are both visible and styled in the correct manner as per https://www.dropbox.com/home/00_web_team/_developer.ubuntu.com/dev.ubuntu.com_09_2016/codelabs/exports?preview=Card+-+Style.jpg
Issue https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/7 relates

Add tags and date to cards

---

src/elements/codelabs-card.html

Change meta info (date and tags) font size to 1em (16px)
Run polymer serve and make sure the font size has changed from 14px to 16px

Change meta font size

---

src/codelabs-page.html
src/codelabs/basic-snap-usage/index.ubuntu-template.html
src/codelabs/build-a-nodejs-service/index.ubuntu-template.html
src/codelabs/create-first-snap/index.ubuntu-template.html
src/codelabs/create-your-own-core-image/index.ubuntu-template.html
src/codelabs/setup-ubuntu-core-intel-joule/index.ubuntu-template.html
src/codelabs/using-intel-realsense-sdk/index.ubuntu-template.html

Modify loading of tutorials content.
- Remove duplicated styles across tutorials
- Remove iron-pages nesting
- This PR should solve #47 
- Ensure tutorials load.
- Make sure images load.
- Verify styling of survey and codeblocks matches current style

Modify tutorial loading

---

src/elements/codelabs-card.html

This import is not used, removing it.

Remove unused import

---

CONTRIBUTING.md
HACKING.md
README.md

Add information on how to use the tools to build the site, and how to write content.

Add contributing and hacking files

---

src/elements/codelabs-card.html

Remove tab index from tutorials
Change font size of card actions
Make sure you can tab through the menu and page
Card: https://trello.com/c/kxBqCh2i
Fixes: https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/52

remove negative tabindex

---

config/google-documents

Add ID to build to Snap a Python application
https://docs.google.com/document/d/1cvXAZRkmKExNIOXMUQihQrd8dNZK6f8v4wk020NymuI/edit#heading=h.7sa4zxkhmsum
- ./bin/build-tutorials
- polymer serve
- Check Tutorial is imported

Add Snap a python application tutorial

---

config/google-documents

Add how to snap a website tutorial

---

src/codelabs-index.html
src/elements/tutorials-filters.html

Style search and filters
Check in s/m and l
Designs: https://www.dropbox.com/sh/60rk7dgme9s2dc5/AABd_B5kb_J7MSzqjA_P7iRaa?dl=0&preview=1.Filter.jpg
Card: https://trello.com/c/QqYHIyF9

Style search and filters

---

src/codelabs-index.html
src/elements/tutorials-filters.html

Featuring:
- Working search
- Search result line, showing amount of results
- Working filters
- Working filter clear button
- Show a message if there are no results.

Build filter logic for Tutorials

---

src/codelabs-index.html
src/elements/tutorials-filters.html

Fix desktop view
Check desktop view

Fix large view

---

src/codelabs-index.html
src/elements/tutorials-filters.html

Fix search field and filters
Check in all screen size and in all browsers

Gb filter tweaks

---

CONTRIBUTING.md

As requested, changing the contribution document to our centrally maintained document:
https://docs.google.com/document/d/1u5qmSNIcE8SjuAg6aKjTxOBGWIjBW0kYf01t4Dfw6-U/edit

Update our contribution guideline document link

---

src/elements/codelabs-behaviors.html
src/elements/codelabs-card.html
src/elements/difficulty-indicator.html
src/ubuntu-tutorials-app.html

- Added difficulty to the tutorial cards. 
- Restyled the cards to simplify them
- updated card font colors
`polymer serve`
[Go to the homepage](http://localhost:8080)
Compare the page to [the designs](https://www.dropbox.com/s/hu4frwgqthl6pbe/Difficulty%20level.jpg?dl=0)
Check all viewports

add difficulty indicator to cards and update related styling

---

src/elements/difficulty-indicator.html

Updated the difficulty indicator sprite to be an svg
- `polymer serve` 
- see that the indicator is now an SVG (and scales nicely without blurriness)

update png image to svg to avoid blurriness

---

src/codelabs-index.html
src/elements/tutorials-filters.html
src/ubuntu-tutorials-app.html

Amend search and filter styles based on design review checklist
Make sure the changes in the card checklist https://trello.com/c/QqYHIyF9 have been made (WIP)

Filter styling tweaks

---

src/elements/tutorials-filters.html

Add disabled attribute to the clear forms, currently with no styling.
This work is going into the feature branch to be styled shortly.
@grahambancroft

Disable clear filter button as needed (no styling)

---

src/elements/tutorials-filters.html

Make extra filter fields optional

---

src/codelabs-index.html
src/elements/tutorials-filters.html

Add bottom margin to search
Make sure drop downs are ubuntu font

filter tweaks

---

src/codelabs-index.html

Remove rounded corners on webkit
Check the search input on mobile webkit

Remove rounded corners on webkit

---

index.html

Move Google Tag Manager to the body, as recommended by Google.

Move Tag Manager snippet to body

---

index.html

Adding Google verification code so that I can access the webmaster tools.
I tried other methods with no luck, so I will add this to verify then remove it once I have access.

Add temporary Google verification

---

config/google-documents

This is the new advanced snap usage tutorial (in gdoc)

Add advanced snap usage tutorial

---

tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for upgrading Ubuntu

add tutorial - upgrading ubuntu

---

tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a USB drive on Windows

Tutorial usb on windows

---

tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md
tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a USB drive on macOS

Tutorial usb on macos

---

tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for installing Ubuntu desktop

Tutorial install ubuntu desktop

---

tutorials/burn-a-dvd-on-windows/burn-a-dvd-on-windows.md
tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md
tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a DVD on Windows

Tutorial dvd on windows

---

tutorials/burn-a-dvd-on-ubuntu/burn-a-dvd-on-ubuntu.md
tutorials/burn-a-dvd-on-windows/burn-a-dvd-on-windows.md
tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md
tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a DVD  on Ubuntu

Tutorial dvd on ubuntu

---

tutorials/burn-a-dvd-on-macos/burn-a-dvd-on-macos.md
tutorials/burn-a-dvd-on-ubuntu/burn-a-dvd-on-ubuntu.md
tutorials/burn-a-dvd-on-windows/burn-a-dvd-on-windows.md
tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md
tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a DVD on macos 

Tutorial dvd on macos

---

tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for installing Ubuntu server

Tutorial install ubuntu server

---

tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a verifying an Ubuntu ISO

Tutorial verify

---

tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/how-to-verify-ubuntu/how-to-verify-ubuntu.md
tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/install-ubuntu-server/install-ubuntu-server.md
tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Created new tutorial for creating a USB drive on Ubuntu

Tutorial usb on ubuntu

---

tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md
tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md
tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
tutorials/upgrading-ubuntu-1604/upgrading-ubuntu-1604-tutorial.md

* Shortened the titles of tutorials that were going onto three lines
* start the service
* see that all the titles are two lines max

shorten titles to two lines

---

tutorials/install-ubuntu-server/install-ubuntu-server.md

Typo in server install tutorial

---

examples/guidelines-snap-tutorials.md

* General cleanup
* New metadata step
* Add author metadata
* no command prompt in snippets

Guidelines cleanup

---

tutorials/install-ubuntu-desktop/install-ubuntu-desktop-1604.md

- added missing details and various other bits.
- updated words and images.

updated images and words.

---

tutorials/burn-a-dvd-on-macos/burn-a-dvd-on-macos.md

Review for #245 
* "Overview" step
* Info box for verfying the ISO
* Durations

Update copy of 'How to burn a DVD on macOS'

---

tutorials/burn-a-dvd-on-windows/burn-a-dvd-on-windows.md

Review for #246 
* Overview step
* Small copy tweaks
* Author

Update copy of  'How to burn a DVD on Windows'

---

tutorials/get-started-hadoop-spark/get-started-hadoop-spark.md

A small PR to change the Hadoop tutorial published date to today's date.

Update Hadoop tutorial to today's date

---

tutorials/install-ubuntu-server/install-ubuntu-server.md

Ubuntu Server install: revised words and images.

---

tutorials/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md

How to write a USB stick with Ubuntu: updated words and images.

---

tutorials/lxd/use-cuda-within-lxd/use-cuda-within-lxd.md

Converted CUDA tutorial for t.u.c. with additional details.

---

tutorials/gdoc.def
tutorials/snap/create-your-own-core-image.md

Convert create-your-own-core-image to Markdown

---

tutorials/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md

fixes #250 
hopefully fixes #278 too (works with my 2013 Macbook Pro, but certainly needs wider testing)

Create a bootable USB stick on macOS: updated words and images.

---

tutorials/gdoc.def
tutorials/snap/using-intel-realsense-sdk.md

N.B., this is not exactly the same as the original. The nested lists in the original were handled very badly!
Original:
New:
this also exposes a style issue - the spacing between text in a list and a new nested list item is way too big! i will file an issue about this

Convert realsense tutorial

---

tutorials/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md

USB stick on Windows tutorial: updated words and images

---

src/elements/tutorials-filters.html

Add filter entries base on the tutorials we have.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>

tutorials-filters: add filter entries

---

tutorials/get-started-canonical-kubernetes/get-started-canonical-kubernetes.md

I've attempted to tread lightly on this:
- Updated formatting and style for markdown
- Fixed a few small problems
- Added brief intro and clarification on credentials with JAAS

Get started with Canonical Kubernetes:  Formatting and styling for markdown

---

tutorials/try-ubuntu-before-you-install/try-ubuntu-before-you-install.md

Try Ubuntu before you install it: Updated words and images

---

tutorials/snap/create-your-own-core-image.md

Deleted the word "it" as does not make sense.

"Those refers to the store account it" typo

---

tutorials/desktop/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md

fixes #305 
fixes #310 
- updated images and words
- tested

macOS bootable USB tutorial: replace UNetbootin with Etcher

---

tutorials/kubernetes/install-kubernetes-with-conjure-up.md

Wrote a new tutorial for installing kubernetes with conjure-up.
- `./run serve tutorials`
- Go to [the tutorial](http://localhost:8016/tutorial/install-kubernetes-with-conjure-up) in your browser

New tutorial for installing k8s with conjure-up

---

tutorials/kubernetes/install-kubernetes-with-conjure-up.md

Reduced the 18 minute deployment step to 13 minutes for accuracy.

K8s conjure up

---

tutorials/desktop/windows-ubuntu-hyperv-containers/windows-ubuntu-hyperv-containers.md

There's a superfluous line break which carries through to the HTML and causes strange line wrapping. KIWF.

Remove superfluous line break in Docker/Win

---

tutorials/desktop/windows-ubuntu-hyperv-containers/windows-ubuntu-hyperv-containers.md

* Update title to fit on two lines
* Use Linux instead of Ubuntu in title: search engine optimization
* containers: lowercase

Containers on Windows: title update

---

tutorials/desktop/windows-ubuntu-hyperv-containers/windows-ubuntu-hyperv-containers.md

7-Zip also has a friendlier UI in addition to its terminal-friendly 7z.exe, and due to its licence there’s a chance it will already be installed.

7-Zip as alternative to XZ utils

---

tutorials/packaging/snap-a-python-application.md

Add git install step

---

tutorials/iot/setup-ubuntu-core-joule.md

Add power supply requirement for the Intel Joule

---

tutorials/packaging/snap-a-python-application.md

"snap try" with sudo

---

tutorials/server/ssh-keygen-windows/ssh-keygen.windows.md

A new tutorial explaining how to generate SSH keys on Windows 10.

Tutorial: Generate SSH Keys on Windows 10

---

CONTRIBUTING.md

...+ some other clarifications

Completely drop gdocs from contribution guidelines

---

metadata/categories.yaml

- Updated categories.yaml with dropdown categories, to allow developers.ubuntu.com to pull in proper api feeds
- Check that the categories.yaml file matches the category dropdown on the homepage

Updated categories.yaml with dropdown categories

---

images/Helpful-no-24px.svg
images/Helpful-unsure-24px.svg
images/Helpful-yes-24px.svg
src/codelabs-page.html
src/elements/tutorial-feedback.html

~~For demo purposes~~
Fixes #342

Tutorials feedback plumbing

---

src/elements/tutorial-feedback.html

Button tooltips

---

.dockerignore
Dockerfile
bower.json
index.html
package.json
polymer.json
src/codelabs-index.html
src/codelabs-page.html
src/elements/tutorials-app-header.html
src/error-404.html
src/ubuntu-tutorials-app.html
yarn.lock

Please review after: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/399
Add Dockerfile and dockerignore for building web app image
Build and run the docker image:
``` bash
./run clean
./run build
./run exec yarn run build-all
docker build --tag tutorials-site --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run --rm -p 8080:8080 tutorials-site
```
Go to http://127.0.0.1:8080 and enjoy.

Add Dockerfile

---

tutorials/desktop/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md

Add note on USB/Windows tutorial

---

src/codelabs-page.html
src/elements/tutorial-feedback.html

Move the feedback form attaching logic into the `google-codelab-ready` javascript event. This event is fired from the codelab itself once it is rady, so this should avoid any async worries.
Attach the feedback form to the `.inner` element of the codelab step to position the form correctly.
Look at the demo and check the feedback form. Make sure it loads correctly.

Update feedback form attachment

---

package.json

- Make APIs build in the main build command.
- Clean the generated api and tutorial files when running the clean command
- Run `./run build && ./run exec yarn run build-all`
- Check the API folder for files such as `./api/tutorials/recent.json`
- Run `./run clean`
- Check that the `api` folder and `src/codelabs` folders are deleted

Add API build script and and clean compiled tutorials

---

examples/guidelines-snap-tutorials.md

Many content fixes in order to make this a part of our published list. These changes help taking readers from an idea to a published tutorial and give them some insights into the review process. 
A follow up PR will take care of the technical aspects of the publication as this tutorial doesn't live in the main tutorials directory.
TODO: fix summary in metadata

Many changes and fixes to the example tutorial

---

examples/example-tutorial.md
tutorials/community/tutorial-guidelines.md

Fix indent in tutorials tutorial code block example

---

tutorials/packaging/basic-snap-usage/basic-snap-usage.md

Fix unclosed parenthesis

---

tutorials/packaging/basic-snap-usage/basic-snap-usage.md

Signed-off-by: Neal Gompa <ngompa13@gmail.com>

Update Fedora instructions for setting up snapd

---

tutorials/packaging/snap-a-website.md

Fixed the style in a code snippet to be more consistent with the rest of the tutorial.

Minor code style fix

---

tutorials/desktop/install-ubuntu-desktop/install-ubuntu-desktop-1604.md
tutorials/id/install-ubuntu-desktop/install-ubuntu-desktop-1604-tutorial-id.md

Translate Install Ubuntu Desktop to Indonesia Language

Translate to indonesian language

---

tutorials/server/install-and-configure-samba/install-and-configure-samba.md

Small metadata fixes related to #534

samba tutorial - metadata: adjusts status, adds feedback_url

---

tutorials/packaging/create-your-first-snap.md
tutorials/packaging/snap-a-website.md

Small updates in cli output, screenshots and wording to give a more accurate description of the store workflow.

Update snap store flow to match new UX

---

src/codelabs-page.html
src/elements/codelabs-card.html

Use assets.ubuntu.com for gci assets

---

tutorials/server/ubuntu-on-windows/ubuntu-on-windows.md

- removed references to Windows Insider program
- updated tutorial to reflect new installation process
- updated images

Ubuntu on Windows: Expunge Windows Insider requirement

---

src/codelabs-index.html

Proposal for new intro content.

Change intro content

---

tutorials/packaging/continuous-snap-delivery-from-circle-ci/continuous-snap-delivery-from-circle-ci.md

I changed `id` in the frontmatter. Not sure if that will break any URLs or if any redirects are needed.

Small grammar fixes for CircleCI tutorial.

---

test/lint-metadata.js
tutorials/packaging/basic-snap-usage/basic-snap-usage.md
tutorials/server/install-and-configure-apache/install-and-configure-apache.md

Update linter to check against common metadata mispellings

---

tutorials/containers/install-kubernetes-with-conjure-up.md

In light of legal advice re pages on ubuntu.com, I have added a registered trademark symbol and disclaimer statement.

Added trademark details to Kubernetes tutorial

---

tutorials/containers/kubeapps-on-canonical-kubernetes/kubeapps-on-canonical-kubernetes.md

In light of legal advice, re pages on ubuntu.com, I have added a registered trademark symbol and disclaimer to this content.

Added register trademark info re Kubernetes

---

tutorials/server/setup-zfs-storage-pool/setup-zfs-storage-pool.md

Release the zfs tutorial

---

tutorials/desktop/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md

Update of the USB drive formatting screenshot to a newer version, matching the steps listed above it.
Fixes #662 , thanks to @rishabhsrao.
http://tutorials.ubuntu.com-pr-663.run.demo.haus/tutorial/tutorial-create-a-usb-stick-on-macos#2

create-a-usb-stick-on-macos: update USB drive formatting screenshot

---

tutorials/containers/install-openstack-with-conjure-up/install-openstack-with-conjure-up.md

Added proxy settings for lxd

---

tutorials/desktop/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md

At create-a-usb-stick-on-ubuntu, a verb was missing

[Tutorials Content] Typo

---

tutorials/desktop/install-ubuntu-desktop/install-ubuntu-desktop-1604.md

Fix typo in desktop tutorial

---

tutorials/desktop/install-ubuntu-on-chromebook/install-ubuntu-on-chromebook.md

Add ref to Tegra CPU in Chromebook tutorial

---

tutorials/server/install-ubuntu-server/install-ubuntu-server-1604.md
tutorials/server/install-ubuntu-server/install-ubuntu-server.md

also moves existing tutorial and renames it to reference 16.04

Add 18.04 server tutorial

---

tutorials/desktop/create-a-usb-stick-on-ubuntu/create-a-usb-stick-on-ubuntu.md

Updated `create USB stick tutorial on Ubuntu`

---

tutorials/desktop/upgrading-ubuntu-1604/upgrading-ubuntu-tutorial.md

Updated upgrade tutorial to include instructions on forcing an update

---

tutorials/server/install-and-configure-apache/install-and-configure-apache.md

Error in name of the file "000-default.conf"

fix: 000-default.conf copy command 

---

tutorials/desktop/firefox-for-web-developers/firefox-for-web-developers.md

Modified the first page to clarify that no experience is necessary, but that it might be useful - with a link to the MDN getting started guide.

Edit first page to add a link to the MDN getting started page

---

HACKING.md

Improving the documentation!
Read it and see if it makes sense.

Improve app documentation

---

tutorials/containers/candid-authentication-lxd/candid-authentication-lxd.md

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

candid: Fix broken first page

---

tutorials/packaging/create-your-first-snap/create-your-first-snap.md

* The snap distribution of snapcraft might be considered more reliable than the APT distribution and is featured in the [official docs](https://forum.snapcraft.io/t/get-started-with-snapcraft/8101), prefer the former over the latter.
* Additional documentation about *classic confinement* has been added.
Fixes #692.

Create your first snap: Use snap distribution of snapcraft

---

src/codelabs-index.html
src/elements/tutorials-app-header.html

Changed the text in the hero section as per the [design spec](https://github.com/ubuntudesign/web-squad/issues/914)
Fixes https://github.com/canonical-websites/tutorials.ubuntu.com/issues/876

Tutorials homepage hero 876

---

index.html

- Add Google site verification meta

Added Google site verification meta

---

.circleci/config.yml
.eslintrc
package.json
polymer.json
renovate.json
src/codelabs-index.html
yarn.lock

This is a fork of https://github.com/canonical-web-and-design/tutorials.ubuntu.com/pull/931, so I can rebase and update to latest renovate config.
I QAed, it works. I'm gonna self-merge.

All renovate updates

---

.circleci/config.yml
Dockerfile
entrypoint
package.json

- upgrade from xenial to bionic
- upgrade node from 6.X to 10.X
- Fix bash var defined or not in `start-server`
- `./run build`
- `./run yarn run build-all`
- `docker build --build-arg COMMIT_ID=dfgd --tag tutorials . && docker run -ti -p 8016:80 tutorials`
- http://0.0.0.0:8016
- go on the website and make sure functionnalities still work

Update dockerfile from xenial to bionic

---

Dockerfile

- `./run build`
- `./run yarn run build-all`
- `docker build --build-arg COMMIT_ID=dfgd --tag tutorials . && docker run -ti -p 8016:80 tutorials`
- http://0.0.0.0:8016
- go on the website and make sure functionnalities still work

Use default npm and nodejs from bionic

---

tutorials/containers/install-a-local-kubernetes-with-microk8s/install-a-local-kubernetes-with-microk8s.md

Update the way we access the dashboard.
Update the command outputs to show coredns.
[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]
[if relevant, include a screenshot]

Updates in microk8s for v1.15

---

tutorials/server/how-to-install-onlyoffice-on-ubuntu

I would like to propose the tutorial on two alternative ways to install ONLYOFFICE on Ubuntu using provided script

how-to-install-onlyoffice-on-ubuntu

---

tutorials/server/how-to-install-onlyoffice-on-ubuntu.md

Move onlyoffice images to the assets server
- Check openoffice tut and verify images appear correctly.

Move onlyoffice images to the assets server

---

tutorials/iot/ubuntu-kiosk/electron-kiosk.md

[iot] electron tutorial fixes

---

tutorials/containers/install-microk8s-on-mac-os/install-microk8s-on-mac-os.md

Signed-off-by: ammarn911 <49419471+ammarn911@users.noreply.github.com>
- MicroK8s Mac OS tutorial
- Test on tutorials staging server please.

MicroK8s on Mac OS Tutorial

---

tutorials/containers/install-microk8s-on-windows/install-microk8s-on-windows.md

Created install-microk8s-on-windows.md
MicroK8s Tutorial for Windos PC
- Please review and test instructions.
- Please review tutorial layout on staging environment.

MicroK8s Windows Tutorial

---

tutorials/desktop/upgrading-ubuntu-1604/upgrading-ubuntu-tutorial.md

Remove references to EoL releases.

Update release info

---

tutorials/containers/install-a-local-kubernetes-with-microk8s/install-a-local-kubernetes-with-microk8s.md

The example shows an incrrect network interface in the UFW rule.
[List of work items including drive-bys]
[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]
Issue: https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/1066
[Related Issue](https://github.com/ubuntu/microk8s/issues/513#issuecomment-537067493)

Change UFW rule to target network interface

---

tutorials/iot/ubuntu-kiosk/electron-kiosk.md
tutorials/iot/ubuntu-kiosk/x11-kiosk.md

Update Xwayland based "kiosk" tutorial

Kiosk tutorials update
