canonical-web-and-design/tutorials.ubuntu.com

src/ubuntu-tutorials-app.html
We are not using this effect and it is creating a console error for missing `condensed-title`
=> Remove unused scroll effect

src/codelabs-page.html
This will pull in the needed codelab components for polymer build. I am refactoring this
page currently to improve the loading of tutorials. This will allow them
to work on staging while waiting
=> Add google codelabs components import for polymer build

src/elements/codelabs-card.html
Add top border radius to cards
Check that the cards have a 2px border radius at the top 
Fix issue https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/24
=> Add top border radius to cards

src/elements/codelabs-card.html
Fix #28 bottom-padding should be 46px
Bottom padding (height) to be consistent
Check staging in Chrome and you’ll see that the bottom section of the cards, (the level and duration bit) is 36px high, this is wrong, it should be 46px which is the same as Safari. It is now.
=> Fix #28 bottom-padding should be 46px

src/codelabs-index.html
Make cards 100% width whenst is small
Fixes issue https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/15
=> card should fit 100% width on mobile when in 1 col

src/codelabs-index.html
Add external icon
Make intro normal paragraph font size
Make link live on its’ own line
Fix issue https://github.com/ubuntudesign/tutorials.ubuntu.com/issues/33
=> Intro copy link needs external icon

index.html
We are having some problems with the service worker on Firefox.
Temporarily disable it while we look into the solution
=> Remove service worker while we work on stability

api/codelabs.json, src/codelabs/basic-snap-usage/codelab.json, src/codelabs/basic-snap-usage/index.ubuntu-template.html, src/codelabs/build-a-nodejs-service/codelab.json, src/codelabs/build-a-nodejs-service/index.ubuntu-template.html, src/codelabs/create-first-snap/codelab.json, src/codelabs/create-first-snap/index.ubuntu-template.html, src/codelabs/create-your-own-core-image/codelab.json, src/codelabs/create-your-own-core-image/index.ubuntu-template.html, src/codelabs/setup-ubuntu-core-intel-joule/codelab.json, src/codelabs/setup-ubuntu-core-intel-joule/index.ubuntu-template.html, src/codelabs/using-intel-realsense-sdk/codelab.json, src/codelabs/using-intel-realsense-sdk/index.ubuntu-template.html
Update tutorials. Primarily, there is a title and content change for RealSense tutorial.
This also fixes #64, replacing issue links.
=> Update tutorials and fix issue link

src/codelabs/basic-snap-usage/index.ubuntu-template.html
Add missing spaces into the html template of basic-snap-usage.
This issue was not found in other pages with command:
grep -r "[0-9a-zA-Z]<a " *.html
This fixes #68
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
=> basic-snap-usage: add missing space before links

LICENSE.md, README.md
This matches the license used on www.ubuntu.com.
Also mention the license in the README, and improve the existing wording.
Resolves #80.
=> License this codebase with LGPL v3

README.md
It took me a while to work out that I needed to install bower dependencies to get Polymer running.
Update the install instructions to reflect this.
=> Mention bower in instructions

.gitignore, bin/build-api-feeds
Add a new `build-api-feeds` Python script to create API feeds for external use.
This builds an API ordered by `updated` field, descending. It then creates files based on filtering by category, and then by filtering by event.
The file format, with optional event and category, is: `api/tutorials/[event/]recent[-category].json`
I moved event to a subfolder because it started to look a bit messy in the filename.
The script also adds some fields to the items:
- `link` to hold the full URL to live tutorial
- `difficultyName` to hold a human readable difficulty
```
➜  ./bin/build-api-feeds
./api/tutorials/recent.json
./api/tutorials/recent-snap.json
./api/tutorials/recent-snapcraft.json
./api/tutorials/idf-2016/recent.json
```
Please run the command, and check the file output.
=> Add script to build API files

config/google-documents
We have been requested to remove the website snap for now, this just removes the ID from the build list.
=> Remove website snap tutorial

src/codelabs-index.html
Change `let` keywords to `var` as it breakes the `polymer build` bundled.
Run `polymer build` and there should be no errors
=> Remove let which is breaking polymer build

config/google-documents
This reverts the previous commit to remove the website snap tutorial, as requested by Didier.
=> Revert "Remove website snap tutorial"

src/elements/codelabs-card.html
Fixed the issue where differing height content broke the display of the card
Check that the cards now display the same height, regardless of description. (You can edit the content in-browser to test)
=> add fixed-height to cards

src/elements/difficulty-indicator.html
Fixed a display bug where the difficulty levels are reversed
`polymer serve`
Look at the cards, inspect the difficulty bars and see that they reflect the hidden text in the span.
=> fix for the difficulty indicator reversal

.gitignore, bin/prerender, polymer.json
Add a script to render pages on the site into static pages to serve for SEO.
The output is not perfect but that is something to improve on.
We want to create a service to return this output on demand but this is a simplified first step towards that.
For QA, we will use live server with official prerender.io service.
For actual use, there is a prerender service installed on the build server and we will use a local server for source.
`./bin/prerender --prerender-host=https://service.prerender.io --src-host=https://tutorials.ubuntu.com`
This should output a tree of files in a `static` folder, which we can serve as needed.
=> Add prerender command to generate static HTML pages

src/elements/websocket-reloader.html, src/ubuntu-tutorials-app.html
The local server (run by bin/serve) enables working incrementally on local
files referred by a codelab.
Everytime a codelab is changed, the modification is picked, corresponding
codelab is rebuilt and a signal is sent to all connected websockets to refresh
the website for this or those codelabs. This refresh is filtered client-side
to match corresponding tutorial name in the url. If not, it's a no-op.
We do reconnect the socket if it was able to connect successfully once and
then was disconnected. The effect is that on production server which won't have
that feature, we attempt to connect once, fail, but don't retry.
=> Add websocket connection for live refresh on local server

bin/downloader_common
Save it under a new filename before swapping the binaries. Now async download
(on serve) works as expected and won't fail on running binary.
=> Fix async download issue by making the download transactional

bower.json, index.html, src/codelabs-index.html, src/codelabs-page.html, src/elements/codelabs-card.html, src/ubuntu-tutorials-app.html
This does a couple of changes to improve the site for search engine crawling.
Some changes are specifically aimed at the prerender.io service.
The commits show a better breakdown but here is a list:
- Pages (index / tutorial) correctly lazy load as needed and dependencies are separated.
- Tutorials API content is moved to main app file to share data and run alongside page loads.
- Page title and description is successfully updated on Tutorial pages.
Some slightly awkward steps, sorry!
- Clone https://github.com/prerender/prerender
- In a background terminal: `npm i` prerender dependencies and run with `node server.js`
- (back in this repo) `bower i` to get latest dependencies.
- Generate example content with `./bin/generate examples`
- `polymer build`
- Start server `polymer serve -p 8083 …
=> Improve page loading and add HTML metadata

CONTRIBUTING.md, HACKING.md, README.md
Update the documentation to simplify and make it much clearer how to contribute.
I am thinking about further improvements to the Issues and PR sections but I think this is a good starting point.
=> Update documentation for markdown and `./run`

examples/guidelines-snap-tutorials.md
Put metadata in a yaml table, formatted nicely on github. This requires the
header (page title) to be set after that the metadata table, but it's still
readable.
Move comments on guidelines between the page title and first section (ignored).
The parser side didn't need any change for those.
=> Change guidelines formatting to be more readable on github

bin/build-api-feeds, examples/guidelines-snap-tutorials.md, src/codelabs-index.html, src/elements/codelabs-card.html, src/elements/tutorials-filters.html
We moved in the claat tool from "updated" to a manually set "published" keyword. Setting it explicitely helps in particular on the markdown files, as creations and modifications time aren't kept when git cloning them.
That way, we control by updating the published key any creation and major updates. This is valid for both gdoc and markdown files.
* Updated read keys for website and external API parser
* Add it to the tutorial markdown example with some comments
=> Use a new published keyword instead of updated

tutorials/gdoc.def
It's clunky and broken, using and showcasing technologies we don't support anymore.
=> Drop the snap-a-website tutorial

src/elements/codelabs-card.html
I think the lack of title attribute on the card `<a>` tag is causing Google to generate confusing results titles:
This commit hopefully fixes it.
=> Add a "title" attribute to the card <a> tag

src/codelabs-page.html
* Overrides the upstream base img styling https://github.com/googlecodelabs/codelab-components/blob/0b8dcb6458290d02e6ff9cdc0430d9c03973bbf3/step-style.html#L188
* Avoids blurriness and allows for smaller images in content.
=> Override for images being forced at 100% width

tutorials/snap/create-your-own-core-image.md
* "Those refer" instead of "Those refers".
* `sudo dd if joule.img` -> `sudo dd if=joule.img`
* store account as a prereq
* link to the account page when needing the id value
=> Create core image - typos and link

src/elements/codelabs-card.html
Move around Tutorial cards to move inside the card-content class which is used by paper-card element.
This should correct the missing padding in the cards.
Fixes #312
=> Restructure Tutorial card to fix margin

.eslintignore, .eslintrc, .stylelintignore, .stylelintrc, .stylelintrc.yaml, .travis.yml, index.html, package.json, src/codelabs-index.html, src/codelabs-page.html, src/elements/codelabs-behaviors.html, src/elements/codelabs-card.html, src/elements/difficulty-indicator.html, src/elements/time-pretty.html, src/elements/tutorials-app-header.html, src/elements/tutorials-filters.html, src/elements/websocket-reloader.html, src/ubuntu-tutorials-app.html, yarn.lock
Added linting steps with a Travis CI step.
This is set up with eslint and stylelint.
The tooling is a little different because the JS and CSS is inline and using later features which tripped up our other tools. There is also the benefit of using a Google backed eslint rules for Polymer.
```
./run test
```
When reviewing local site or demo, the site should look and act the same.
=> Add linting, testing, and CI

examples/guidelines-snap-tutorials.md
As we have started using `feedback-link` on production, we might as well add it to the guidelines.
=> Add feedback-link metadata to guidelines

tutorials/kubernetes/install-kubernetes-with-conjure-up.md
Updated the k8s with conjure=up tutorial content based on the feedback from @tvansteenburgh 
- `./run serve turorials`
- Navigate to the [tutorial](http://localhost:8016/tutorial/install-kubernetes-with-conjure-up)
- Check that the tone reads better than the previous version and that all comments in #319 have been addressed.
Fixes #319
=> conjure-up/k8s: Tone update and clarifications added.

polymer.json, src/codelabs-page.html, src/elements/tutorials-app-header.html, src/error-404.html, src/ubuntu-tutorials-app.html
This adds a 404 page following the style of www.ubuntu.com.
This is initial work towards #200 but this is not complete and we will want to have a bigger project to improve this in the near future.
I have a feeling the demo service won't allow you to see it easily.
I am testing by running `polymer serve` directly and visiting a fake URL, without the run command.
=> New 404 page

src/codelabs-index.html
- Fixed sorting errors on chromium-based browsers (date, duration and difficulty)
- Changed _getSortFunction to return integers (-1, 1) instead of truthiness
- View the site locally in your web browser at: [http://localhost:8016]
- Check that the sorting works as intended on Chrome and Firefox
Fixes #304
=> Fixed tutorial sorting errors on chrome

src/elements/tutorials-app-header.html, src/ubuntu-tutorials-app.html
- Fixed back button on tutorial pages
- Reordered location of tutorial-header in main app page (was a problem in lifecycle - hidden function was firing before relevant attributes loaded in)
- View the site locally in your web browser at: [http://localhost:8016]
- Check that the back button works as intended on any tutorial page
Fixes #173
=> Fixed back button on tutorial page

src/elements/codelabs-card.html
If no # number is present while loading a tutorial, Codelabs will add it
to the current location and creates an extra item in the history. This
means you have to click back twice to return out of a tutorial.
This avoids this step.
In the demo, click a tutorial and then hit back. It should only take one step to return to the home page.
=> Append #0 in links to avoid extra browser history

src/codelabs-page.html
- Added backURL property to codelabs-page that stores the referrer URL if it exists
- Changed default google-codelab goToHome function to custom one that redirects to backURL
- View the site locally in your web browser at: [http://localhost:8016]
- Check that the header back button redirects to referrer if linked to from another site
- Otherwise it should redirect to index
- **NOTE** document.referrer is null when directed from HTTPS to HTTP, so it will only work on the demo server and http://localhost when the referrer is also an HTTP site (see [here](https://www.e-nor.com/blog/google-analytics/https-to-http-secure-to-nonsecure-referrer-loss))
Fixes #356
=> Added functionality to header back button to return to referrer

src/codelabs-index.html, src/elements/tutorials-filters.html
- Fixed size of search bar so it's the same as the filter/sort dropdowns
- Changed the alignment of the filter/sort dropdowns so that they're on the same line on large screens, and full-width on small screens
- Made the search/filter/sorts more responsive
- Minor design changes
- View the site locally in your web browser at: [http://localhost:8016](http://localhost:8016)
- Check that the search/filter/sort bars on the index page are the same size, and align correctly for small and large screens
Fixes #165  Fixes #166
=> Fixed search and filter bars and made them responsive

src/codelabs-index.html
- Added 10px padding-left to no results search message so it aligns with the rest of the page
- Check that the no results search message lines up with the rest of the page
Fixes #162
=> Fixed padding on no results search message

src/codelabs-index.html, src/elements/codelabs-card.html, src/elements/tutorials-filters.html
- Made tutorial cards responsive for tablet-size displays
- General alignment and responsiveness fixes (search and filter bars now aligned with borders, difficulty/duration strip now stacks when card thins)
- Check that the tutorial cards are responsive at all screen sizes. 3 cards per row for large screens (901px+), 2 for medium screens (625px - 900px), 1 for small screens (624px-)
Fixes #164
=> Made cards responsive for tablet-size displays

src/codelabs-index.html
- Fixed search bar styling on mobile Safari by removing border-radius
- Search bars were given webkit-appearance of none in an earlier commit
- Check that styling of search bar is the same as the filter dropdowns on small screen Safari browser
Fixes #156
=> Fixed search bar styling on mobile Safari

src/codelabs-index.html, src/elements/tutorials-filters.html
- Made dropdown lists the same width as the dropdown menu for all sizes (i.e 'Filter by results' + 'Sort by results')
- Check that the dropdown lists that appear when you click 'Filter results by' and 'Sort results by' are the same width as the menu itself
Fixes #158
=> Made dropdown width same as filter/sort list

bower.json, index.html, package.json, polymer.json, src/codelabs-index.html, src/codelabs-page.html, src/elements/tutorials-app-header.html, src/error-404.html, src/ubuntu-tutorials-app.html, yarn.lock
Update Polymer to 1.11 and enable prpl-server.
This:
- Updates Polymer and index.html initialisation
- Installs prpl-server and creates yarn script
- Improvements to page loading and metadata. Which helps prepare for rendertron.
- `./run clean && ./run` - make sure it all functions the same.
- Run locally to test `prpl-server`:
- `./run clean`
- `yarn install`
- `bower install`
- `yarn run build-all`
- `yarn run prpl-server`
Have a click around and check the functionality of the site.
=> Upgrade Polymer and add prpl-server

package.json
Set prpl-server to serve on port 80 as default.
- `yarn install`
- `bower install`
- `yarn run build-all`
- `yarn run prpl-server`
- Site should be accessible on http://localhost:80
=> Set default port on prpl-server to 80

src/codelabs-index.html, src/elements/tutorials-app-header.html, src/ubuntu-tutorials-app.html
Stop Chrome creating the header with no size so that it looks unstyled (until you resize the browser).
- Update the header styling to force a size across nested elements.
- Also set the main app file and tutorials list pages to use iron layout classes.
Check output in multiple browsers and check the header looks correct on first load.
=> Force full width styling on header on first load.

src/codelabs-page.html, src/ubuntu-tutorials-app.html
Fix some styling regressions created on `/tutorial/*` pages:
- Set font family, size, and weight on header.
- Set tutorial wrapper to have a transparent background and not block primary background.
Compare a Tutorial on demo and live. The header should looks the same.
You should see the background image correctly.
=> Correct tutorial page styling

polymer.json, src/elements/websocket-reloader.html
The es6-unbundled build is generating 404 errors on our Kubernetes deployment, when accessed with Chrome. This disables the build falling back to es6-bundled.
This disabled the build that is causing us problems and I will create an issue to investigate and correct the problem.
This also limits the websocket-reloader to only running on non HTTPS localhost, preventing a secure error on deployment.
`./run exec yarn run build-all` and check the builds happen correctly.
An image for this is currently on Docker hub and can be checked by reviewing https://github.com/canonical-webteam/deployment-configs/pull/17
Issue created to investigate and revert work: https://github.com/canonical-websites/tutorials.ubuntu.com/issues/410
=> Remove es6-unbundled build and limit dev-reloader

src/codelabs-page.html
This is to fix #73.
The codelab element sets a `title=""` attribute. In Chrome, this is fine. In Firefox it creates a tooltip that pops up anywhere on the page when you stop moving your mouse.
I tried unsetting the title with Javascript but it also unsets the title text in the header bar.
This isn't my favourite method but that tooltip is quite annoying and I would really like to stop it.
- Check demo in Firefox, don't see a tooltip when you hover on a tutorial page!
=> Stop tooltips on Firefox by setting title on a child

tutorials/packaging/snap-a-website.md
~~This is a draft.~~
How to snap a website with Electron. Ready for review.
Demo: http://tutorials.ubuntu.com-pr-412.run.demo.haus/tutorial/snap-a-website
Note that this tutorial is not relying on the electron-builder snap integration since it doesn't use cleanbuild and produces broken snaps on 17.10.
=> Add new tutorial draft

tutorials/packaging/basic-snap-usage/basic-snap-usage.md, tutorials/packaging/snap-a-nodejs-app.md, tutorials/packaging/snap-a-python-application.md
Fixes the broken link to "Create your first snap" on 3 tutorials.
Example: 
The second bullet point under "Next Steps" on this page has a broken link.
https://tutorials.ubuntu.com/tutorial/basic-snap-usage#5
=> Repoint "Create your first snap" links

index.html, src/codelabs-index.html, src/codelabs-page.html, src/elements/codelabs-card.html, src/elements/tutorial-feedback.html, src/elements/tutorials-filters.html
Since last week, all fonts on the site look bold on webkit browsers. This fixes it without any style regression on both Firefox and Chromium-based browsers (tested on Chrome/Chromium/Vivaldi).
=> Switch to Ubuntu Light

index.html, src/codelabs-index.html, src/codelabs-page.html, src/elements/codelabs-card.html, src/elements/tutorial-feedback.html, src/elements/tutorials-filters.html
Reverts canonical-websites/tutorials.ubuntu.com#501
Revert the changes for now while we improve font loading for Ubuntu Light.
=> Revert "Switch to Ubuntu Light"

package.json
This will proxy bots if the environment variable is set. If the address
does not exist it falls back to serving directly. This will be used for
internal DNS usage in our production servers
(Need to run yarn locally to test as ./run can't forward the port from the exec command)
- `yarn install`
- `bower install`
- `PORT=8016 BOT_PROXY=http://fake-rendertron/render yarn run prpl-server`
- `curl -H http://localhost:8016` - Returns 200
- `curl -IH "User-Agent: Slackbot" http://localhost:8016"` - Will show a `ENOTFOUND` error in prpl-server output and return a 200 (a little slower)
=> Set prpl-server to proxy bots to http://rendertron

src/codelabs-index.html, src/codelabs-page.html
Set the backURL to explicitly accept URL parameters correctly, while
making sure that the link is not an external URL when hitting the back
button. If it is an external URL, we will not use the pushstate API.
- `./run serve`
- Hitting the back button in a Tutorial titlebar should work correctly
- Adding `?backURL=https://www.ubuntu.com` (before the `#`) should send you to ubuntu.com
=> Set backURL logic

src/codelabs-page.html
This makes the back button always go to the homepage, unless the backURL parameter is explicitly set.
1. Click on http://tutorials.ubuntu.com-pr-563.run.demo.haus/tutorial/kubeapps-on-canonical-kubernetes (or http://localhost:8016/tutorial/kubeapps-on-canonical-kubernetes)
2. click on the back button next to the title
3. Ensure you are moved to the homepage of tutorials and not github.com
=> Disable automatic backurl

index.html
This brings fonts served from assets.ubuntu.com as opposed to Google webfonts only. This fixes the bold Ubuntu font issue seen on Chromium-based browsers.
1. On Ubuntu, open https://tutorials.ubuntu.com in Chrome and Firefox, fonts on Chrome should look much bolder.
2. Now compare http://tutorials.ubuntu.com-pr-581.run.demo.haus/ in Chrome and Firefox, fonts should look much thinner (pretty close to Firefox on step 1)
=> Ubuntu font self-serving

src/codelabs-index.html
If it exists, the index now passes the "q" parameter from the URL to the search field.
* Ensure http://tutorials.ubuntu.com-pr-586.run.demo.haus/?q=snapcraft fills up the search input with "snapcraft" and returns snapcraft related tutorials
* Ensure the correct search is applied when the search field is changed afterwards
* Ensure http://tutorials.ubuntu.com-pr-586.run.demo.haus/?q= returns all tutorials
* Ensure http://tutorials.ubuntu.com-pr-586.run.demo.haus/?q=foo returns no tutorials
=> Get search keywords from URL q param

test/lint-metadata.js
A duplicated tutorial ID can lead to pretty bad things, such as a localized tutorial overriding the URL of the default one, if the translator has not checked if the ID was different from the original.
The metadata linter now checks for duplicates.
1. Change the ID of a tutorial to match the ID of another one
2. `./run tests` shoud fail
=> Update linter to check for duplicated tutorial ids

tutorials/containers/kubeapps-on-canonical-kubernetes/kubeapps-on-canonical-kubernetes.md
We no longer need to use `--channel edge` to workaround https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/451
=> kubeapps: remove use of `--channel edge` workaround

tutorials/server/enable-the-livepatch-service/enable-the-livepatch-service.md
Fix Ubuntu Forums URL in the Canonical Livepatch tutorial (ubuntuforums.org instead of community.ubuntu.com).
community.ubuntu.com page is not for technical support. While creating this tutorial, I didn't know about this and I gave a wrong URL. This pull request fixes it.
=> Fix Ubuntu Forums URL in Livepatch tutorial

src/codelabs-index.html
- Added a footer to the bottom of the index page, styled like that from www.ubuntu.com
- Includes copyright, Legal Information, Cookie policy and Report a bug links
- View the site locally in your web browser at: http://localhost:8016/
- Check that there is a footer at the bottom of the index page
- Check that clicking each link will redirect you to the right place
Fixes #311
=> 311: Add footer to index page

index.html, polymer.json
Set unresolved attribute on body. It helps prevent flashing of unstyled content.
Once Polymer has loaded, it removes this attribute
Explicity set build option to compile Javascript as default.
- `./run` and check the site removes the unresolved attribute on load.
- `./run exec yarn polymer-build` should run without errors
=> Render and build improvement

Dockerfile, index.html, package.json, polymer.json, robots.txt, server.js, src/codelabs-page.html, src/ubuntu-tutorials-app.html, yarn.lock
This extends the prpl-server used in production. It adds mittleware to set headers and HTML head.
The key features:
- Send correct 404 headers on non existant `/tutorials/*` and `/api/*` URLs.
- Set metadata in the output, looking up correct data from codelabs API.
- Add a `sitemap.xml` to link to every tutorial, and a robots.txt to link to sitemap
QA'ing this will require not using the ./run script.
- `yarn run clean`
- `yarn install`
- `yarn run build-all`
- `PORT=8081 yarn run start-server`
I have been testing metadata output with:
`http http://0.0.0.0:8081/tutorial/install-openstack-with-conjure-up\#0 -p hb | rg -e 'HTTP.*$' -e '<title>[^<]*</title>' -e '<meta[^>]*>' -e '<[^<>]*canonical[^>]*>' -o`
(Using `httpie` for web request, and `rg`/`ripgrep` is a really nice grep replacement) …
=> Extend prpl-server with SEO magic

tutorials/packaging/continuous-snap-delivery-from-circle-ci/continuous-snap-delivery-from-circle-ci.md
This greatly simplifies the configuration necessary, and means we need to explain less. It also stops using a feature that will soon cost money (the machine executor).
=> circleci tutorial: use the snapcraft docker image

examples/example-tutorial.md, tutorials/community/tutorial-guidelines.md
This adds the "image" metadata field to the guidelines and example.
* This optional field takes an image link that will be used in opengraph metadata when building the static page served to bots and scripts.
The two prerequisites commits to handle this metadata in the md parser have been merged upstream: 
* https://github.com/didrocks/codelab-ubuntu-tools/pull/1
* https://github.com/Ubuntu/tutorial-deployment/pull/4
* Add an image field to a tutorial
* run `npm run build-all`
* run `PORT=8081 yarn run start-server`
* Go to `localhost:8081/<tutorial you changed>`, inspect meta tags of the page and ensure "og:image" is correctly set.
=> Add image metadata in examples

tutorials/containers/use-cuda-within-lxd/use-cuda-within-lxd.md
* Add goals
* Add logos
* Drop Requirements step and move content to Overview
- Go to http://tutorials.ubuntu.com-pr-658.run.demo.haus/tutorial/gpu-data-processing-inside-lxd#0
- Compare the "Overview" step with https://tutorials.ubuntu.com/tutorial/gpu-data-processing-inside-lxd#0
- Confirm the new page looks slightly more appealing :)
=> Improve CUDA tutorial overview page, add logos and goals

src/codelabs-page.html
This adds a check for the root domain of backURL values against a whitelist of domains, to avoid abuse of the backURL feature.
'ubuntu.com',
'snapcraft.io',
'jujucharms.com',
'maas.io',
'conjure-up.io',
'netplan.io',
'canonical.com',
'launchpad.net',
'linuxcontainers.org',
'cloud-init.io',
'vanillaframework.io',
'github.com'
Ensure clicking on the back arrow of the following tutorial URLs takes you to:
**the homepage of the tutorials site**:
- http://tutorials.ubuntu.com-pr-674.run.demo.haus/tutorial/tutorial-guidelines?backURL=https://uboontu.com
- http://tutorials.ubuntu.com-pr-674.run.demo.haus/tutorial/tutorial-guidelines?backURL=https://www.uboontu.com
- http://tutorials.ubuntu.com-pr-674.run.demo.haus/tutorial/tutorial-guidelines?backURL=https://docs.uboontu.com
**ubuntu.com or …
=> Check backURL values against a whitelist of domains

src/ubuntu-tutorials-app.html
- Apply tabindex to app component and listen for focus and apply focus to main container element
- [Fixes #615](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/615#event-1505915524)
=> Make main container focusable so is keyboard accessible

tutorials/packaging/snap-a-website.md
Update of the electron tutorial to make the snap work with other input methods such as fcitx
=> Update electron tutorial to use desktop-gtk2 instead of desktop-glib-only

tutorials/desktop/how-to-verify-ubuntu/how-to-verify-ubuntu.md
This fixes a minor typo in the tutorial.
=> Fix typo in gpg --list-keys call

tutorials/desktop/how-to-verify-ubuntu/how-to-verify-ubuntu.md
Short key IDs are insecure: it's possible and in fact quite easy for
somebody to generate a key that collides with the short key ID for
cdimage and upload it to the keyservers.  Use long key IDs instead to
greatly increase the difficulty of this attack.
=> Use long GnuPG key IDs

package.json, redirects.json, server.js, yarn.lock
Add redirects to work with renamed tutorials in PR #828.
This should be merged alongside that PR.
- Build `./run exec yarn run build-all`
- Run the site using the command `./run exec -p 8016 yarn run start-server`
- Check the redirects are correct with curl
```sh
curl -I localhost:8016/tutorial/graphical-snaps
curl -I localhost:8016/tutorial/graphical-snaps
```
=> Add redirects for renamed tutorials

tutorials/iot/ubuntu-kiosk/electron-kiosk.md, tutorials/iot/ubuntu-kiosk/secure-ubuntu-kiosk.md, tutorials/iot/ubuntu-kiosk/ubuntu-web-kiosk.md, tutorials/iot/ubuntu-kiosk/wayland-kiosk.md, tutorials/iot/ubuntu-kiosk/x11-kiosk.md
- Fixed links back to tutorials in all ubuntu-kiosk tutorials
- Fixed x11-kiosk title
- Check that the links in http://0.0.0.0:8016/tutorial/secure-ubuntu-kiosk#3 are working fine - linking to other tutorials
=> [iot] fix internal links in ubuntu-kiosk

tutorials/desktop/create-a-usb-stick-on-windows/create-a-usb-stick-on-windows.md
Rufus is misspelled Refus on line 94 of "create-a-usb-stick-on-windows.md"
=> Fix typo in "create-a-usb-stick-on-windows.md"

tutorials/packaging/create-your-first-snap/create-your-first-snap.md
Snap building is only compatible with the same base system that the snap is targeted against (currently `xenial`), make sure that students won't attempt to build a snap package on Ubuntu >16.04 cause it won't work.
The snapcraft package hints are dropped due to:
* It is already mentioned in the next section
* It won't work with non-Ubuntu distributions even if the same package is in their repository due to base system incompatibilities.
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> Fix development environment requirement in Create your first snap

tutorials/packaging/create-your-first-snap/create-your-first-snap.md
This patch fixes the outdated/informal term use of the snapcraft lifecycle
* s/stage/step/
* s/snap step/pack step/
Refer-to: Snapcraft lifecycle - doc - snapcraft.io <https://forum.snapcraft.io/t/snapcraft-lifecycle/5123>
=> Fix snapcraft lifecycle terms in Create your first snap

tutorials/packaging/create-your-first-snap/create-your-first-snap.md
This patch drops invalid code from the example recipe, seems to be a trivial copy & paste error.
=> Drop invalid code in Create your first snap

tutorials/packaging/create-your-first-snap/create-your-first-snap.md
This patch mainly emphasizes the YAML data types and the exact reason to
add the quoting, so the readers will get the idea logically.
Misc. changes:
* Replace ('`2.10`') with (`'2.10'`) as the single quotes are part of the
code.
* Add code formatting to the `version` keyword
* Drop the forced line wrapping as the rendered result is clearly subject to the
line endings
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
=> Fix quoted version note in Create your first snap

src/codelabs-index.html, src/elements/tutorials-app-header.html
Moved the search bar top to the header as per [design spec](https://github.com/ubuntudesign/web-squad/issues/914)
- Check out the search bar on the homepage and see if it matches the [design spec](https://github.com/ubuntudesign/web-squad/issues/914)
Fixes https://github.com/canonical-websites/tutorials.ubuntu.com/issues/871
=> Moved search bar top

tutorials/packaging/create-your-first-snap/create-your-first-snap.md
* Fixes the wrong value of the $SNAP environment variable at https://tutorials.ubuntu.com/tutorial/create-your-first-snap#4
=> Create your first snap: Fix system snap directory

tutorials/iot/ubuntu-kiosk/electron-kiosk.md, tutorials/iot/ubuntu-kiosk/secure-ubuntu-kiosk.md, tutorials/iot/ubuntu-kiosk/ubuntu-web-kiosk.md, tutorials/iot/ubuntu-kiosk/wayland-kiosk.md, tutorials/iot/ubuntu-kiosk/x11-kiosk.md
Update the Mir-kiosk IoT guides to reflect:
- adopt core18 by default
- use newer snapcraft/snapd features
- Follow the tutorials and ensure the steps are correct
=> [iot] update kiosk guide to reflect snapd/snapcraft changes

tutorials/containers/install-a-local-kubernetes-with-microk8s/install-a-local-kubernetes-with-microk8s.md
- Updated broken link
Fixes: https://github.com/ubuntu/microk8s/issues/670
=> Fix link to charmed kubernetes

tutorials/containers/kubeflow-tutorial/kubeflow-tutorial.md
Improves the Kubeflow tutorial. This PR shortens the intro page, pushing the explanatory information about each technology into another section.
Paragraphs poorly when published to the web. The commit also folds multiple sentences of the same  paragraph onto the same line. This allows the browser to reflow paragraphs as it needs to.
- Condense the intro, promoting the "What you'll learn" section
- Move "about the tools" into separate page 
- Put paragraphs onto single line
- Improve capitalisation in (jupyter -> Jupyter,  "Create A VM" -> "Create a VM")
n/a
[if relevant, include a screenshot]
=> Improve text wrapping in Kubeflow tutorial

tutorials/containers/charmed-kubernetes-kata-containers/charmed-kubernetes-kata-containers.md
This patchset adds the tutorial for Kata Containers on Charmed
Kubernetes.
[List of work items including drive-bys]
[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]
[if relevant, include a screenshot]
=> Kata Containers tutorial
